spring:
  application:
    name: sme-stocksense-backend
  profiles:
    active: neon
  config:
    # Đã sửa classpath: thành file:
    import: optional:file:.env[.properties]
  flyway:
    validate-on-migrate: false # <--- THÊM ĐÚNG 2 DÒNG NÀY VÀO ĐÂY

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true