spring:
  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
