CREATE TABLE "bien_ban_chenh_lech" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phieu_nhap_id" BIGINT UNIQUE NOT NULL,
  "ma_bien_ban" varchar(50) UNIQUE NOT NULL,
  "ngay_lap" timestamp NOT NULL DEFAULT now(),
  "nguoi_lap_id" BIGINT NOT NULL,
  "ghi_chu" varchar(255),
  "ngay_tao" timestamp NOT NULL DEFAULT now(),
  "ngay_cap_nhat" timestamp NOT NULL DEFAULT now(),
  "version" BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE "chi_tiet_bien_ban_chenh_lech" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bien_ban_id" BIGINT NOT NULL,
  "san_pham_id" BIGINT NOT NULL,
  "so_luong_chung_tu" INT NOT NULL,
  "so_luong_thuc_te" INT NOT NULL,
  "so_luong_lech" INT NOT NULL,
  "ly_do" varchar(255),
  "huong_xu_ly" varchar(255),
  "ngay_tao" timestamp NOT NULL DEFAULT now(),
  "ngay_cap_nhat" timestamp NOT NULL DEFAULT now(),
  "version" BIGINT NOT NULL DEFAULT 0
);

ALTER TABLE "bien_ban_chenh_lech" ADD FOREIGN KEY ("phieu_nhap_id") REFERENCES "phieu_nhap_kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bien_ban_chenh_lech" ADD FOREIGN KEY ("nguoi_lap_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_bien_ban_chenh_lech" ADD FOREIGN KEY ("bien_ban_id") REFERENCES "bien_ban_chenh_lech" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chi_tiet_bien_ban_chenh_lech" ADD FOREIGN KEY ("san_pham_id") REFERENCES "san_pham" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE UNIQUE INDEX ON "chi_tiet_bien_ban_chenh_lech" ("bien_ban_id", "san_pham_id");

CREATE INDEX IF NOT EXISTS "idx_bb_cl_phieu_nhap_id" ON "bien_ban_chenh_lech" ("phieu_nhap_id");
CREATE INDEX IF NOT EXISTS "idx_ct_bb_cl_bien_ban_id" ON "chi_tiet_bien_ban_chenh_lech" ("bien_ban_id");

COMMENT ON TABLE "bien_ban_chenh_lech" IS 'Bien ban ghi nhan chenh lech giua thuc te kiem hang va chung tu goc.';
COMMENT ON TABLE "chi_tiet_bien_ban_chenh_lech" IS 'Chi tiet san pham chenh lech kem ly do va huong xu ly.';
