CREATE TABLE "phieu_nhap_kho_lich_su" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phieu_nhap_id" bigint NOT NULL,
  "nguoi_thuc_hien_id" bigint NOT NULL,
  "hanh_dong" varchar(50) NOT NULL,
  "ghi_chu" varchar(500),
  "ngay_thuc_hien" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "phieu_nhap_kho_lich_su" ADD FOREIGN KEY ("phieu_nhap_id") REFERENCES "phieu_nhap_kho" ("id") ON DELETE CASCADE;
ALTER TABLE "phieu_nhap_kho_lich_su" ADD FOREIGN KEY ("nguoi_thuc_hien_id") REFERENCES "nhan_vien" ("id");
