CREATE TYPE "trang_thai_nhan_vien" AS ENUM (
  'HOAT_DONG',
  'TAM_KHOA',
  'NGUNG_HOAT_DONG'
);

CREATE TYPE "ma_vai_tro_he_thong" AS ENUM (
  'ADMIN',
  'MANAGER',
  'EMPLOYEE'
);

CREATE TYPE "loai_doi_tac" AS ENUM (
  'NHA_CUNG_CAP',
  'KHACH_HANG',
  'CA_HAI'
);

CREATE TYPE "trang_thai_chung_tu_kho" AS ENUM (
  'NHAP',
  'CHO_DUYET',
  'DA_DUYET',
  'TU_CHOI',
  'HOAN_THANH',
  'HUY'
);

CREATE TYPE "loai_giao_dich_kho" AS ENUM (
  'NHAP_KHO',
  'XUAT_KHO',
  'NHAP_DAU_KY',
  'DIEU_CHINH_TANG',
  'DIEU_CHINH_GIAM'
);

CREATE TYPE "trang_thai_import" AS ENUM (
  'CHO_XU_LY',
  'CO_LOI',
  'SAN_SANG_IMPORT',
  'DA_IMPORT',
  'THAT_BAI'
);

CREATE TYPE "trang_thai_canh_bao" AS ENUM (
  'MOI',
  'DA_XEM',
  'DA_XU_LY'
);

CREATE TYPE "muc_do_canh_bao" AS ENUM (
  'THAP',
  'TRUNG_BINH',
  'CAO',
  'KHAN_CAP'
);

CREATE TABLE "vai_tro" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_vai_tro" ma_vai_tro_he_thong UNIQUE NOT NULL,
  "ten_vai_tro" varchar(100) NOT NULL,
  "mo_ta" varchar(255),
  "ngay_tao" timestamp,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "nhan_vien" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ho_ten" varchar(150) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "mat_khau" varchar(255) NOT NULL,
  "so_dien_thoai" varchar(30),
  "vai_tro_id" bigint NOT NULL,
  "trang_thai" trang_thai_nhan_vien NOT NULL DEFAULT 'HOAT_DONG',
  "ngay_tao" timestamp,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "doi_tac" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_doi_tac" varchar(50) UNIQUE NOT NULL,
  "ten_doi_tac" varchar(150) NOT NULL,
  "loai_doi_tac" loai_doi_tac NOT NULL,
  "so_dien_thoai" varchar(30),
  "email" varchar(150),
  "dia_chi" varchar(255),
  "dang_hoat_dong" boolean NOT NULL DEFAULT true,
  "ngay_tao" timestamp,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "danh_muc" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_danh_muc" varchar(50) UNIQUE NOT NULL,
  "ten_danh_muc" varchar(150) NOT NULL,
  "mo_ta" varchar(255),
  "ngay_tao" timestamp,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "kho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_kho" varchar(50) UNIQUE NOT NULL,
  "ten_kho" varchar(150) NOT NULL,
  "dia_chi" varchar(255),
  "dang_hoat_dong" boolean NOT NULL DEFAULT true,
  "ngay_tao" timestamp,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "san_pham" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_san_pham" varchar(50) UNIQUE NOT NULL,
  "ten_san_pham" varchar(200) NOT NULL,
  "sku" varchar(100) UNIQUE,
  "ma_vach" varchar(100) UNIQUE,
  "don_vi_tinh" varchar(50) NOT NULL,
  "danh_muc_id" bigint,
  "doi_tac_cung_cap_id" bigint,
  "ton_toi_thieu" int NOT NULL DEFAULT 0,
  "ton_toi_da" int,
  "thoi_gian_giao_hang" int NOT NULL DEFAULT 1,
  "dang_hoat_dong" boolean NOT NULL DEFAULT true,
  "ngay_tao" timestamp,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "ton_kho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "san_pham_id" bigint NOT NULL,
  "kho_id" bigint NOT NULL,
  "so_luong" int NOT NULL DEFAULT 0,
  "ngay_cap_nhat" timestamp
);

CREATE TABLE "giao_dich_kho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "san_pham_id" bigint NOT NULL,
  "kho_id" bigint NOT NULL,
  "loai_giao_dich" loai_giao_dich_kho NOT NULL,
  "so_luong" int NOT NULL,
  "so_luong_truoc" int NOT NULL,
  "so_luong_sau" int NOT NULL,
  "phieu_nhap_id" bigint,
  "phieu_xuat_id" bigint,
  "lan_import_id" bigint,
  "ghi_chu" varchar(255),
  "nguoi_tao_id" bigint,
  "ngay_tao" timestamp
);

CREATE TABLE "phieu_nhap_kho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_phieu_nhap" varchar(50) UNIQUE NOT NULL,
  "doi_tac_id" bigint,
  "kho_id" bigint NOT NULL,
  "trang_thai" trang_thai_chung_tu_kho NOT NULL DEFAULT 'NHAP',
  "tong_tien" decimal(15,2),
  "ghi_chu" varchar(255),
  "nguoi_tao_id" bigint,
  "ngay_tao" timestamp,
  "nguoi_gui_duyet_id" bigint,
  "ngay_gui_duyet" timestamp,
  "nguoi_duyet_id" bigint,
  "ngay_duyet" timestamp,
  "ly_do_tu_choi" varchar(500),
  "ngay_hoan_thanh" timestamp
);

CREATE TABLE "chi_tiet_phieu_nhap" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phieu_nhap_id" bigint NOT NULL,
  "san_pham_id" bigint NOT NULL,
  "so_luong" int NOT NULL,
  "don_gia" decimal(15,2),
  "thanh_tien" decimal(15,2),
  "ghi_chu" varchar(255),
  "ngay_tao" timestamp
);

CREATE TABLE "phieu_xuat_kho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_phieu_xuat" varchar(50) UNIQUE NOT NULL,
  "doi_tac_id" bigint,
  "kho_id" bigint NOT NULL,
  "trang_thai" trang_thai_chung_tu_kho NOT NULL DEFAULT 'NHAP',
  "tong_tien" decimal(15,2),
  "ghi_chu" varchar(255),
  "nguoi_tao_id" bigint,
  "ngay_tao" timestamp,
  "nguoi_gui_duyet_id" bigint,
  "ngay_gui_duyet" timestamp,
  "nguoi_duyet_id" bigint,
  "ngay_duyet" timestamp,
  "ly_do_tu_choi" varchar(500),
  "ngay_hoan_thanh" timestamp
);

CREATE TABLE "chi_tiet_phieu_xuat" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phieu_xuat_id" bigint NOT NULL,
  "san_pham_id" bigint NOT NULL,
  "so_luong" int NOT NULL,
  "don_gia" decimal(15,2),
  "thanh_tien" decimal(15,2),
  "ghi_chu" varchar(255),
  "ngay_tao" timestamp
);

CREATE TABLE "lan_import_excel" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_file" varchar(255) NOT NULL,
  "duong_dan_file" varchar(255),
  "loai_import" varchar(50) NOT NULL DEFAULT 'TON_DAU_KY',
  "kho_id" bigint NOT NULL,
  "trang_thai" trang_thai_import NOT NULL DEFAULT 'CHO_XU_LY',
  "tong_so_dong" int DEFAULT 0,
  "so_dong_hop_le" int DEFAULT 0,
  "so_dong_loi" int DEFAULT 0,
  "nguoi_tao_id" bigint,
  "ngay_tao" timestamp,
  "ngay_hoan_thanh" timestamp
);

CREATE TABLE "loi_import_excel" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lan_import_id" bigint NOT NULL,
  "so_dong" int,
  "ten_cot" varchar(100),
  "gia_tri_goc" varchar(255),
  "noi_dung_loi" varchar(255),
  "goi_y_sua" varchar(255),
  "ngay_tao" timestamp
);

CREATE TABLE "canh_bao_ton_kho" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "san_pham_id" bigint NOT NULL,
  "kho_id" bigint NOT NULL,
  "ton_hien_tai" int NOT NULL,
  "ton_toi_thieu" int NOT NULL,
  "muc_do" muc_do_canh_bao NOT NULL DEFAULT 'TRUNG_BINH',
  "trang_thai" trang_thai_canh_bao NOT NULL DEFAULT 'MOI',
  "noi_dung" varchar(255),
  "ngay_tao" timestamp,
  "ngay_xu_ly" timestamp,
  "nguoi_xu_ly_id" bigint
);

CREATE UNIQUE INDEX ON "ton_kho" ("san_pham_id", "kho_id");

CREATE UNIQUE INDEX ON "chi_tiet_phieu_nhap" ("phieu_nhap_id", "san_pham_id");

CREATE UNIQUE INDEX ON "chi_tiet_phieu_xuat" ("phieu_xuat_id", "san_pham_id");

COMMENT ON TABLE "vai_tro" IS 'MVP chi dung 3 role co dinh: ADMIN, MANAGER, EMPLOYEE. Khong lam RBAC chi tiet trong giai doan dau.';

COMMENT ON TABLE "nhan_vien" IS 'Nhan su dang nhap he thong. Moi nhan vien co 1 role chinh trong MVP.';

COMMENT ON TABLE "doi_tac" IS 'Doi tac co the la nha cung cap, khach hang hoac ca hai.';

COMMENT ON TABLE "danh_muc" IS 'Danh muc san pham.';

COMMENT ON TABLE "kho" IS 'Kho hang cua 1 doanh nghiep SME. Khong tach ke/vi tri/khu vuc trong MVP.';

COMMENT ON TABLE "san_pham" IS 'San pham trong kho. ton_toi_thieu dung cho canh bao ton kho MVP.';

COMMENT ON TABLE "ton_kho" IS 'Ton kho hien tai theo san pham va kho.';

COMMENT ON TABLE "giao_dich_kho" IS 'So lich su bien dong ton kho. Tao khi phieu hoan thanh hoac import ton dau ky.';

COMMENT ON TABLE "phieu_nhap_kho" IS 'Phieu nhap kho. Khi HOAN_THANH moi tang ton kho.';

COMMENT ON TABLE "chi_tiet_phieu_nhap" IS 'Chi tiet san pham trong phieu nhap.';

COMMENT ON TABLE "phieu_xuat_kho" IS 'Phieu xuat kho. Khi HOAN_THANH moi tru ton kho.';

COMMENT ON TABLE "chi_tiet_phieu_xuat" IS 'Chi tiet san pham trong phieu xuat.';

COMMENT ON TABLE "lan_import_excel" IS 'Moi lan upload Excel theo template. MVP khong luu tung dong hop le vao DB, chi luu tong quan va loi.';

COMMENT ON TABLE "loi_import_excel" IS 'Luu loi import de hien thi cho nguoi dung sua file Excel.';

COMMENT ON TABLE "canh_bao_ton_kho" IS 'MVP canh bao khi ton_hien_tai <= ton_toi_thieu. Sau nay co the mo rong them ket_qua_du_bao_id.';

ALTER TABLE "nhan_vien" ADD FOREIGN KEY ("vai_tro_id") REFERENCES "vai_tro" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "san_pham" ADD FOREIGN KEY ("danh_muc_id") REFERENCES "danh_muc" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "san_pham" ADD FOREIGN KEY ("doi_tac_cung_cap_id") REFERENCES "doi_tac" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ton_kho" ADD FOREIGN KEY ("san_pham_id") REFERENCES "san_pham" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ton_kho" ADD FOREIGN KEY ("kho_id") REFERENCES "kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "giao_dich_kho" ADD FOREIGN KEY ("san_pham_id") REFERENCES "san_pham" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "giao_dich_kho" ADD FOREIGN KEY ("kho_id") REFERENCES "kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "giao_dich_kho" ADD FOREIGN KEY ("phieu_nhap_id") REFERENCES "phieu_nhap_kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "giao_dich_kho" ADD FOREIGN KEY ("phieu_xuat_id") REFERENCES "phieu_xuat_kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "giao_dich_kho" ADD FOREIGN KEY ("lan_import_id") REFERENCES "lan_import_excel" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "giao_dich_kho" ADD FOREIGN KEY ("nguoi_tao_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("doi_tac_id") REFERENCES "doi_tac" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("kho_id") REFERENCES "kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("nguoi_tao_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("nguoi_gui_duyet_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_nhap_kho" ADD FOREIGN KEY ("nguoi_duyet_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_phieu_nhap" ADD FOREIGN KEY ("phieu_nhap_id") REFERENCES "phieu_nhap_kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_phieu_nhap" ADD FOREIGN KEY ("san_pham_id") REFERENCES "san_pham" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_xuat_kho" ADD FOREIGN KEY ("doi_tac_id") REFERENCES "doi_tac" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_xuat_kho" ADD FOREIGN KEY ("kho_id") REFERENCES "kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_xuat_kho" ADD FOREIGN KEY ("nguoi_tao_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_xuat_kho" ADD FOREIGN KEY ("nguoi_gui_duyet_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phieu_xuat_kho" ADD FOREIGN KEY ("nguoi_duyet_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_phieu_xuat" ADD FOREIGN KEY ("phieu_xuat_id") REFERENCES "phieu_xuat_kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chi_tiet_phieu_xuat" ADD FOREIGN KEY ("san_pham_id") REFERENCES "san_pham" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lan_import_excel" ADD FOREIGN KEY ("kho_id") REFERENCES "kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lan_import_excel" ADD FOREIGN KEY ("nguoi_tao_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "loi_import_excel" ADD FOREIGN KEY ("lan_import_id") REFERENCES "lan_import_excel" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "canh_bao_ton_kho" ADD FOREIGN KEY ("san_pham_id") REFERENCES "san_pham" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "canh_bao_ton_kho" ADD FOREIGN KEY ("kho_id") REFERENCES "kho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "canh_bao_ton_kho" ADD FOREIGN KEY ("nguoi_xu_ly_id") REFERENCES "nhan_vien" ("id") DEFERRABLE INITIALLY IMMEDIATE;
