CREATE TABLE "phieu_xuat_kho_lich_su" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phieu_xuat_id" bigint NOT NULL,
  "nguoi_thuc_hien_id" bigint NOT NULL,
  "hanh_dong" varchar(50) NOT NULL,
  "ghi_chu" varchar(500),
  "ngay_thuc_hien" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_ls_phieu_xuat" FOREIGN KEY ("phieu_xuat_id") REFERENCES "phieu_xuat_kho" ("id") ON DELETE CASCADE,
  CONSTRAINT "fk_ls_phieu_xuat_actor" FOREIGN KEY ("nguoi_thuc_hien_id") REFERENCES "nhan_vien" ("id")
);

CREATE INDEX "idx_ls_phieu_xuat_document" ON "phieu_xuat_kho_lich_su" ("phieu_xuat_id", "ngay_thuc_hien" DESC);
