CREATE TABLE IF NOT EXISTS "quyen" (
    "id"                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ma_quyen"               VARCHAR(100)  NOT NULL,
    "ten_quyen"              VARCHAR(150)  NOT NULL,
    "nhom_quyen"             VARCHAR(100)  NOT NULL,
    "is_system"              BOOLEAN       NOT NULL DEFAULT FALSE,
    "required_permission_id" BIGINT,
    "ngay_tao"               TIMESTAMP     DEFAULT now(),
    "ngay_cap_nhat"          TIMESTAMP     DEFAULT now(),
    CONSTRAINT "uq_quyen_ma_quyen" UNIQUE ("ma_quyen"),
    CONSTRAINT "fk_quyen_required" FOREIGN KEY ("required_permission_id") REFERENCES "quyen" ("id")
);

CREATE TABLE IF NOT EXISTS "vai_tro_quyen" (
    "vai_tro_id" BIGINT NOT NULL,
    "quyen_id"   BIGINT NOT NULL,
    PRIMARY KEY ("vai_tro_id", "quyen_id"),
    CONSTRAINT "fk_vai_tro_quyen_vai_tro" FOREIGN KEY ("vai_tro_id") REFERENCES "vai_tro" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_vai_tro_quyen_quyen"   FOREIGN KEY ("quyen_id")   REFERENCES "quyen"   ("id") ON DELETE CASCADE
);

-- pad: 10_91841382