INSERT INTO "quyen" ("id", "ma_quyen", "ten_quyen", "nhom_quyen", "is_system", "required_permission_id") VALUES
(1, 'MANAGE_EMPLOYEE', 'Quản lý nhân viên', 'HE_THONG', true, null),
(2, 'MANAGE_ROLE_PERMISSION', 'Quản lý vai trò & phân quyền', 'HE_THONG', true, null),
(3, 'MANAGE_WAREHOUSE', 'Quản lý kho', 'DANH_MUC', false, null),
(4, 'MANAGE_CATEGORY', 'Quản lý danh mục', 'DANH_MUC', false, null),
(5, 'MANAGE_PARTNER', 'Quản lý đối tác', 'DANH_MUC', false, null),
(6, 'MANAGE_PRODUCT', 'Quản lý sản phẩm', 'DANH_MUC', false, null),
(7, 'VIEW_IMPORT_ALL', 'Xem tất cả phiếu nhập', 'NHAP_KHO', false, null),
(8, 'VIEW_IMPORT_OWN', 'Xem phiếu nhập của mình', 'NHAP_KHO', false, null),
(9, 'CREATE_IMPORT', 'Tạo phiếu nhập', 'NHAP_KHO', false, null),
(10, 'UPDATE_IMPORT', 'Sửa phiếu nhập (nháp)', 'NHAP_KHO', false, null),
(11, 'SUBMIT_IMPORT', 'Gửi phiếu nhập chờ duyệt', 'NHAP_KHO', false, null),
(12, 'APPROVE_IMPORT_L1', 'Duyệt phiếu nhập cấp 1', 'NHAP_KHO', false, null),
(13, 'APPROVE_IMPORT_L2', 'Duyệt phiếu nhập cấp 2', 'NHAP_KHO', false, 12),
(14, 'REJECT_IMPORT', 'Từ chối phiếu nhập', 'NHAP_KHO', false, null),
(15, 'CANCEL_IMPORT', 'Hủy phiếu nhập', 'NHAP_KHO', false, null),
(16, 'INSPECT_IMPORT', 'Kiểm hàng phiếu nhập', 'NHAP_KHO', false, null),
(17, 'COMPLETE_IMPORT', 'Hoàn tất phiếu nhập', 'NHAP_KHO', false, null),
(18, 'CREATE_DISCREPANCY', 'Lập biên bản chênh lệch', 'NHAP_KHO', false, null),
(19, 'APPROVE_DISCREPANCY', 'Duyệt biên bản chênh lệch', 'NHAP_KHO', false, null),
(20, 'VIEW_EXPORT_ALL', 'Xem tất cả phiếu xuất', 'XUAT_KHO', false, null),
(21, 'VIEW_EXPORT_OWN', 'Xem phiếu xuất của mình', 'XUAT_KHO', false, null),
(22, 'CREATE_EXPORT', 'Tạo phiếu xuất', 'XUAT_KHO', false, null),
(23, 'UPDATE_EXPORT', 'Sửa phiếu xuất (nháp)', 'XUAT_KHO', false, null),
(24, 'SUBMIT_EXPORT', 'Gửi phiếu xuất chờ duyệt', 'XUAT_KHO', false, null),
(25, 'APPROVE_EXPORT', 'Duyệt phiếu xuất', 'XUAT_KHO', false, null),
(26, 'REJECT_EXPORT', 'Từ chối phiếu xuất', 'XUAT_KHO', false, null),
(27, 'COMPLETE_EXPORT', 'Hoàn tất phiếu xuất', 'XUAT_KHO', false, null),
(28, 'EXCEL_UPLOAD_CONFIRM', 'Upload & xác nhận Excel', 'TIEN_ICH', false, null),
(29, 'VIEW_DASHBOARD', 'Xem Dashboard thống kê', 'TIEN_ICH', false, null),
(30, 'VIEW_INVENTORY', 'Xem tồn kho', 'TIEN_ICH', false, null)
ON CONFLICT ("ma_quyen") DO NOTHING;

-- pad: 11_570377043