CREATE TYPE "warehouse_status" AS ENUM (
  'ACTIVE',
  'INACTIVE'
);

CREATE TABLE "warehouses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "name" varchar(150) NOT NULL,
  "address" varchar(255),
  "status" warehouse_status NOT NULL DEFAULT 'ACTIVE',
  "created_at" timestamp,
  "updated_at" timestamp
);

COMMENT ON TABLE "warehouses" IS 'SME warehouse inventory information.';
